/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class vrpn_VRPNDevice */

#ifndef _Included_vrpn_VRPNDevice
#define _Included_vrpn_VRPNDevice
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: downInVrpnLock */
/*
 * Class:     vrpn_VRPNDevice
 * Method:    doingOkay_native
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vrpn_VRPNDevice_doingOkay_1native
  (JNIEnv *, jobject);

/*
 * Class:     vrpn_VRPNDevice
 * Method:    isConnected_native
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vrpn_VRPNDevice_isConnected_1native
  (JNIEnv *, jobject);

/*
 * Class:     vrpn_VRPNDevice
 * Method:    isLive_native
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_vrpn_VRPNDevice_isLive_1native
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
